source $HOME/dotfiles-etc/zsh/.zshrc_plugins

# Set the terminal to one that supports truecolor and italics
export TERM=xterm-256color-italic

# Use neovim as the git editor if it exists
if hash nvim 2>/dev/null; then
  export GIT_EDITOR='nvim'
# Otherwise use vim
else
  export GIT_EDITOR='vim'
fi

# Customize to your needs...
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# Use the git tools installed by homebrew.
export PATH="/usr/local/Cellar/git/2.2.1/bin/:$PATH"

# 10 second wait if you do something that will delete everything.
setopt RM_STAR_WAIT

# This allows rake tasks with parameters
unsetopt nomatch

# Don't do partial globs, just assume the first part of the completion is correct
zstyle ':completion:*' accept-exact '*(N)'

# Cache tab completion results
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache

# Disable hostname completion
zstyle ':completion:*' hosts off

# Insert unambiguous completions automatically
zstyle ':completion:*' insert-unambiguous true

# Use colors in the completions
zstyle ':completion:*' list-colors ''

zstyle ':completion:*' completer _complete _ignored

# Use man files when doing completions
zstyle ':completion:*:manuals'    separate-sections true
zstyle ':completion:*:manuals.*'  insert-sections   true
zstyle ':completion:*:man:*'      menu yes select

# Bigger history
export HISTSIZE=10000

# Erase history duplicates
export HISTCONTROL=erasedups

# Initialize rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Colorize man pages
# via: http://boredzo.org/blog/archives/2016-08-15/colorized-man-pages-understood-and-customized
function man() {
  env \
    LESS_TERMCAP_md=$'\e[1;36m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_se=$'\e[0m' \
    LESS_TERMCAP_so=$'\e[1;40;92m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[1;32m' \
      man "$@"
}

# Set the NVM directory
export NVM_DIR="$HOME/.nvm"

# Setup nvm
[ -f $(brew --prefix nvm)/nvm.sh ] && source $(brew --prefix nvm)/nvm.sh

# Setup fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Load the local zsh settings if available
[ -f ~/.zshrc_local ] && source ~/.zshrc_local

# Use fzf to show a file browser and then edit the selected file in nvim
alias e='nvim $(fzf)'

# Fixes an issue where the webcam freezes up
function fix_camera() {
  sudo killall AppleCameraAssistant
}
